compute_environment: LOCAL_MACHINE
distributed_type: NO
mixed_precision: fp16
use_cpu: false
num_processes: 1
num_machines: 1
machine_rank: 0
main_training_function: main
downcast_bf16: false
deepspeed_config:
  deepspeed_config_file: deepspeed/zero3.json
  zero3_init_flag: true
